#!/usr/bin/env python3
"""Translate Spanish content in Python files"""
import re
from pathlib import Path

# Comprehensive translation map for all Spanish content
TRANSLATION_MAP = {
    # report-generator.py translations
    'REGLAS CRÍTICAS:': 'CRITICAL RULES:',
    'Extensión: 2-3 párrafos máximo (200-300 palabras)': 'Length: 2-3 paragraphs max (200-300 words)',
    'Estructura: Situación → Hallazgos → Recomendación principal': 'Structure: Situation → Findings → Main recommendation',
    'Datos: Siempre incluye números y métricas concretos': 'Data: Always include concrete numbers and metrics',
    'Lenguaje: Evita jerga técnica. Usa "documentos" no "embeddings"': 'Language: Avoid technical jargon. Use "documents" not "embeddings"',
    'Impacto: Destaca el valor de negocio, no la tecnología': 'Impact: Highlight business value, not the technology',
    'Formato: Markdown simple, sin encabezados': 'Format: Simple markdown, no headers',
    'Documentos indexados: ': 'Indexed documents: ',
    'Tamaño total: ': 'Total size: ',
    'Hallazgos clave: ': 'Key findings: ',
    'Recomendación principal: ': 'Main recommendation: ',
    'Escribe resumen ejecutivo en': 'Write executive summary in',
    'Implementación exitosa': 'Successful implementation',
    'Eres analista de documentación de IA.': 'You are an AI documentation analyst.',
    'Convierte datos técnicos en prosa ejecutiva profesional.': 'Convert technical data into professional executive prose.',
    'Mantén tono formal pero accesible.': 'Keep formal but accessible tone.',
    'Analiza estos hallazgos y escribe sección "Hallazgos" en': 'Analyze these findings and write the "Findings" section in',
    'Formato: 3-5 puntos bullet, cada uno con una frase introductoria.': 'Format: 3-5 bullet points, each with an introductory phrase.',
    'Incluye datos específicos. Destaca lo importante.': 'Include specific data. Highlight what is important.',
    'Eres estratega de transformación digital.': 'You are a digital transformation strategist.',
    'Creas recomendaciones accionables y de alto impacto.': 'You create actionable and high-impact recommendations.',
    'Tono: Profesional, inspirador, orientado a resultados.': 'Tone: Professional, inspiring, results-oriented.',
    'Contexto del proyecto:': 'Project context:',
    'Genera 4-5 recomendaciones estratégicas en': 'Generate 4-5 strategic recommendations in',
    '- Cada una debe ser accionable (no vaga)': '- Each one must be actionable (not vague)',
    '- Incluir timeline (corto/medio/largo plazo)': '- Include timeline (short/medium/long term)',
    '- Destaca el valor de negocio': '- Highlight business value',
    'Formato: bullet points con subtítulo.': 'Format: bullet points with subtitle.',
    'Calidad de datos': 'Data quality',
    'Disponibilidad': 'Availability',
    'Fase 1 - Setup Azure': 'Phase 1 - Setup Azure',
    'Fase 2 - Indexación': 'Phase 2 - Indexing',
    'Fase 3 - UAT': 'Phase 3 - UAT',
    'Fase 4 - Producción': 'Phase 4 - Production',
    'RAG: Informe Ejecutivo de Implementación': 'RAG: Executive Implementation Report',
    'Sistema Inteligente de Búsqueda de Documentación': 'Intelligent Documentation Search System',
    'informe-ejecutivo': 'executive-report',
    'Alta calidad de contenido': 'High-quality content',
    '1-2 semanas': '1-2 weeks',
    '1 semana': '1 week',
    '2 semanas': '2 weeks',
    'Documentación bien estructurada': 'Well-structured documentation',
    'Oportunidad de automatización': 'Automation opportunity',
    'Implementación de búsqueda híbrida': 'Hybrid search implementation',
    'Integración con SharePoint': 'SharePoint integration',
    'Documentos indexados': 'Indexed documents',
    'Tamaño total': 'Total size',
    'Proyecto RAG de documentación interna con 2345 documentos': 'Internal documentation RAG project with 2345 documents',
    # report-templates.py translations
    'Profesional y confiado sin ser presuntuoso': 'Professional and confident without being presumptuous',
    'Datos concretos, no especulación': 'Concrete data, not speculation',
    'Enfoque en valor de negocio, no tecnología': 'Focus on business value, not technology',
    'Frases cortas (máx 20 palabras)': 'Short sentences (max 20 words)',
    'Verbos activos (no pasiva)': 'Active verbs (not passive)',
    'Números siempre: "2,345 documentos" no "muchos documentos"': 'Always numbers: "2,345 documents" not "many documents"',
    'Evita: Jerga técnica, puntos grises, disclaimers': 'Avoid: Technical jargon, gray areas, disclaimers',
    'Incluye: Riesgos/oportunidades, timeline, ROI': 'Include: Risks/opportunities, timeline, ROI',
    'Preciso y completo': 'Precise and complete',
    'Diagramas y ejemplos de código': 'Diagrams and code examples',
    'Transparencia sobre limitaciones': 'Transparency about limitations',
    'Referencias a Azure best practices': 'References to Azure best practices',
    'Opciones alternativas cuando proceda': 'Alternative options when appropriate',
    'Mezcla datos duros + contexto de negocio': 'Mix hard data + business context',
    'Accesible para no-técnicos': 'Accessible for non-technical users',
    'Soportado con ejemplos reales': 'Supported with real examples',
    'Destaca impacto en operaciones': 'Highlight operational impact',
    'Informe Ejecutivo: Implementación de Búsqueda Inteligente': 'Executive Report: Intelligent Search Implementation',
    'Resumen Ejecutivo': 'Executive Summary',
    '- 2-3 párrafos máximo': '- 2-3 paragraphs max',
    '- Responda: Qué, cuándo, valor': '- Answer: What, when, value',
    '- Incluya: Número de documentos, plazo, beneficio principal': '- Include: Number of documents, timeline, main benefit',
    '- Tono: Profesional, orientado a resultados': '- Tone: Professional, results-oriented',
    '- Ejemplo: "Se han indexado 2,345 documentos en Azure Search': '- Example: "2,345 documents indexed in Azure Search',
    'permitiendo búsqueda instantánea que reduce el tiempo de consulta': 'enabling instant search that reduces query time',
    'de 15 minutos a 30 segundos."': 'from 15 minutes to 30 seconds."',
    'Situación Actual': 'Current Situation',
    '- Describe el estado antes de la solución': '- Describe the state before the solution',
    '- Incluya: Volumen de documentos, desafíos, costos actuales': '- Include: Document volume, challenges, current costs',
    '- Tono: Neutral, basado en hechos': '- Tone: Neutral, fact-based',
    '- Use bullets para claridad': '- Use bullets for clarity',
    'Solución Propuesta': 'Proposed Solution',
    '- Explique QUÉ se construyó, no CÓMO (nivel ejecutivo)': '- Explain WHAT was built, not HOW (executive level)',
    '- Incluya: Arquitectura conceptual, integraciones': '- Include: Conceptual architecture, integrations',
    '- Opcional: Diagrama simple': '- Optional: Simple diagram',
    '- Destaque: Escalabilidad, seguridad, cumplimiento': '- Highlight: Scalability, security, compliance',
    'Beneficios Cuantificables': 'Quantifiable Benefits',
    '- SIEMPRE números concretos': '- ALWAYS concrete numbers',
    '- Formato: "X% reducción en tiempo de búsqueda"': '- Format: "X% reduction in search time"',
    '- Incluya: Productividad, costos, satisfacción': '- Include: Productivity, costs, satisfaction',
    '- Mínimo 3 beneficios clave': '- Minimum 3 key benefits',
    '- Opcional: ROI (si datos disponibles)': '- Optional: ROI (if data available)',
    'Recomendaciones': 'Recommendations',
    '- 4-5 recomendaciones máximo': '- 4-5 recommendations max',
    '- Estructura: [Recomendación] - [Beneficio] - [Timeline]': '- Structure: [Recommendation] - [Benefit] - [Timeline]',
    '- Priorícelas: Alta/Media/Baja': '- Prioritize: High/Medium/Low',
    '- Incluya costos estimados': '- Include estimated costs',
    '- Horizonte: Corto (1mes)/Medio (3-6m)/Largo (6-12m)': '- Horizon: Short (1mo)/Medium (3-6mo)/Long (6-12mo)',
    'Plan de Implementación': 'Implementation Plan',
    '- Timeline: Fases claras con duración': '- Timeline: Clear phases with duration',
    '- Mínimo: 4 fases (Setup, Indexación, UAT, Producción)': '- Minimum: 4 phases (Setup, Indexing, UAT, Production)',
    '- Incluya: Dependencias, entregables, responsables': '- Include: Dependencies, deliverables, owners',
    '- Tono: Realista (mejor estimar pesimista)': '- Tone: Realistic (better to estimate pessimistically)',
    'Riesgos & Mitigaciones': 'Risks & Mitigations',
    '- Ábrase sobre riesgos (genera confianza)': '- Be open about risks (builds confidence)',
    '- Cada riesgo: descripción + impacto + mitigación': '- Each risk: description + impact + mitigation',
    '- Ejemplo: "Riesgo: Documentos sin indexar. Mitigación:': '- Example: "Risk: Unindexed documents. Mitigation:',
    'Validación de formato, pre-procesamiento automático"': 'Format validation, automatic pre-processing"',
    'Anexos': 'Appendices',
    '- Detalles técnicos, logs, ejemplos de queries': '- Technical details, logs, query examples',
    '- Arquitectura detallada (si hay espacio)': '- Detailed architecture (if space available)',
    '- Matriz de características': '- Feature matrix',
    '- Glosario de términos (si es necesario)': '- Glossary of terms (if needed)',
    'QUALITY_CHECKLIST': 'QUALITY_CHECKLIST',
    '☑ ¿Cada afirmación está soportada por datos?': '☑ Is each statement supported by data?',
    '☑ ¿Se incluyen números concretos (no \'muchos\', \'varios\')?': '☑ Are concrete numbers included (not \'many\', \'several\')?',
    '☑ ¿El resumen ejecutivo tiene máx 300 palabras?': '☑ Is the executive summary max 300 words?',
    '☑ ¿Hay al menos 3 beneficios cuantificables?': '☑ Are there at least 3 quantifiable benefits?',
    '☑ ¿Las recomendaciones son accionables (no vagas)?': '☑ Are recommendations actionable (not vague)?',
    '☑ ¿El tono es profesional pero accesible?': '☑ Is the tone professional yet accessible?',
    '☑ ¿Se evita jerga técnica (o está explicada)?': '☑ Is technical jargon avoided (or explained)?',
    '☑ ¿Los párrafos tienen máx 4 líneas?': '☑ Do paragraphs have max 4 lines?',
    '☑ ¿Se usan verbos activos?': '☑ Are active verbs used?',
    '☑ ¿Los bullet points son paralelos (misma estructura)?': '☑ Are bullet points parallel (same structure)?',
    '☑ ¿Hay introducción con contexto?': '☑ Is there introduction with context?',
    '☑ ¿Hay conclusión clara con next steps?': '☑ Is there clear conclusion with next steps?',
    '☑ ¿Las secciones tienen transiciones?': '☑ Do sections have transitions?',
    '☑ ¿Hay al menos 1 diagrama/tabla?': '☑ Is there at least 1 diagram/table?',
    '☑ ¿Los títulos son descriptivos?': '☑ Are titles descriptive?',
    '☑ ¿Hay 0 errores de ortografía?': '☑ Are there 0 spelling errors?',
    '☑ ¿Hay 0 errores de puntuación?': '☑ Are there 0 punctuation errors?',
    '☑ ¿El formato está consistente (fuentes, tamaños)?': '☑ Is formatting consistent (fonts, sizes)?',
    '☑ ¿Las tablas están bien formateadas?': '☑ Are tables well formatted?',
    '☑ ¿El documento tiene página de portada?': '☑ Does the document have a cover page?',
    '☑ ¿Se menciona el número de documentos indexados?': '☑ Is the number of indexed documents mentioned?',
    '☑ ¿Se menciona el tiempo de respuesta (mejora)?': '☑ Is response time (improvement) mentioned?',
    '☑ ¿Se justifica la tecnología Azure (no genérico)?': '☑ Is Azure technology justified (not generic)?',
    '☑ ¿Hay referencia a security/compliance?': '☑ Is there security/compliance reference?',
    '☑ ¿El ROI o beneficio final está claro?': '☑ Is ROI or final benefit clear?',
    'ESTRUCTURA RECOMENDADA (2-3 párrafos):': 'RECOMMENDED STRUCTURE (2-3 paragraphs):',
    'Párrafo 1 - Contexto:': 'Paragraph 1 - Context:',
    '"El cliente tenía [problema/oportunidad] con [X documentos/proceso].': '"The client had [problem/opportunity] with [X documents/process].  ',
    'Se implementó [solución] usando [tecnología clave]."': 'Implemented [solution] using [key technology]."',
    'Párrafo 2 - Resultados:': 'Paragraph 2 - Results:',
    '"Como resultado, [métrica de impacto 1], [métrica de impacto 2],': '"As a result, [impact metric 1], [impact metric 2],',
    'y [métrica de impacto 3]. El ROI es de [X]% en [timeframe]."': 'and [impact metric 3]. ROI is [X]% in [timeframe]."',
    'Párrafo 3 - Siguiente:': 'Paragraph 3 - Next:',
    '"Se recomienda [acción principal] para [objetivo]. Esto requiere': '"Recommend [main action] for [objective]. This requires',
    '[recursos] y [timeline]. El cliente está listo para [next phase]."': '[resources] and [timeline]. Client is ready for [next phase]."',
    'MÉTRICAS A INCLUIR:': 'METRICS TO INCLUDE:',
    '• Documentos indexados: [número]': '• Indexed documents: [number]',
    '• Tiempo de búsqueda: [antes] → [después]': '• Search time: [before] → [after]',
    '• Disponibilidad: [%]': '• Availability: [%]',
    '• Usuarios impactados: [número]': '• Impacted users: [number]',
    '• Costo anual: [cantidad] (si aplica)': '• Annual cost: [amount] (if applicable)',
    'TONO:': 'TONE:',
    '- Confianza sin arrogancia': '- Confidence without arrogance',
    '- Hechos, no promesas': '- Facts, not promises',
    '- Enfoque en valor, no en tecnología': '- Focus on value, not technology',
    '- Referencia a estándares (Azure, ISO, etc.)': '- Reference to standards (Azure, ISO, etc.)',
    'ESTRUCTURA POR RECOMENDACIÓN:': 'STRUCTURE PER RECOMMENDATION:',
    '[Número]. [Título de Recomendación]': '[Number]. [Recommendation Title]',
    'Descripción: [1-2 frases sobre QUÉ]': 'Description: [1-2 sentences about WHAT]',
    'Beneficio: [Impacto concreto - use números si es posible]': 'Benefit: [Concrete impact - use numbers if possible]',
    'Implementación: [Timeline corto/medio/largo]': 'Implementation: [Short/medium/long timeline]',
    'Inversión estimada: [Si disponible]': 'Estimated investment: [If available]',
    'Prioridad: [Alta/Media/Baja]': 'Priority: [High/Medium/Low]',
    '1. Integrar SharePoint con búsqueda': '1. Integrate SharePoint with search',
    'Descripción: Conectar automáticamente nuevos documentos de': 'Description: Automatically connect new documents from',
    'SharePoint a la búsqueda inteligente, eliminando uploads manuales.': 'SharePoint to intelligent search, eliminating manual uploads.',
    'Beneficio: Reduce tiempo de indexación de 1 hora a 10 minutos,': 'Benefit: Reduces indexing time from 1 hour to 10 minutes,',
    'garantiza documentos siempre actualizados, elimina punto de fallo manual.': 'ensures documents always updated, eliminates manual failure point.',
    'Implementación: 2-3 semanas (corto plazo)': 'Implementation: 2-3 weeks (short term)',
    'Inversión: $0 (aprovecha licencias existentes)': 'Investment: $0 (leverages existing licenses)',
    'Prioridad: Alta': 'Priority: High',
    '"Mejorar el sistema" ← vago, no accionable': '"Improve the system" ← vague, not actionable',
    '"Considerar opciones futuras" ← no concreto': '"Consider future options" ← not concrete',
    '"Optimizar según necesidades" ← no específico': '"Optimize per needs" ← not specific',
    'FASES ESTÁNDAR PARA RAG:': 'STANDARD PHASES FOR RAG:',
    'Fase 1: Preparación (1-2 semanas)': 'Phase 1: Preparation (1-2 weeks)',
    '- Setup Azure, creación de recursos': '- Setup Azure, create resources',
    '- Preparación de documentos': '- Prepare documents',
    '- Entrenamiento de equipo': '- Team training',
    'Fase 2: Implementación (2-4 semanas)': 'Phase 2: Implementation (2-4 weeks)',
    '- Indexación de documentos': '- Document indexing',
    '- Configuración de búsqueda': '- Search configuration',
    '- Tuning de parámetros': '- Parameter tuning',
    'Fase 3: Validación (1-2 semanas)': 'Phase 3: Validation (1-2 weeks)',
    '- UAT con usuarios': '- UAT with users',
    '- Ajustes según feedback': '- Adjustments per feedback',
    '- Documentación final': '- Final documentation',
    'Fase 4: Producción (1 semana)': 'Phase 4: Production (1 week)',
    '- Go-live': '- Go-live',
    '- Monitoreo inicial': '- Initial monitoring',
    '- Handover a soporte': '- Handover to support',
    'TOTAL TÍPICO: 4-8 semanas': 'TYPICAL TOTAL: 4-8 weeks',
    'REGLA: Siempre estima pesimista (+20%)': 'RULE: Always estimate pessimistically (+20%)',
    'Se ha implementado un sistema inteligente de búsqueda sobre 2,345 documentos': 'Implemented an intelligent search system over 2,345 documents',
    'internos de MENSADEF, que cubre procedimientos, legislación, casos de uso y': 'internal to MENSADEF, covering procedures, legislation, use cases and',
    'análisis técnico. Utilizando Azure OpenAI y Azure Search, el sistema permite': 'technical analysis. Using Azure OpenAI and Azure Search, the system enables',
    'búsqueda semántica instantánea que reduce el tiempo de consulta de 15 minutos': 'instant semantic search reducing query time from 15 minutes',
    'a 30 segundos, beneficiando a más de 200 usuarios.': 'to 30 seconds, benefiting 200+ users.',
    'Los resultados iniciales muestran que el 94% de las búsquedas devuelven el': 'Initial results show 94% of searches return the',
    'documento correcto en el primer resultado. Se han validado 500+ casos de uso': 'correct document on first result. Validated 500+ use cases',
    'reales, con una precisión del 97%. El sistema está listo para producción y': 'with 97% precision. System is production-ready and',
    'puede escalarse a 5,000+ documentos sin cambios arquitectónicos.': 'scales to 5,000+ documents without architectural changes.',
    'Se recomienda: (1) activar búsqueda en producción en la próxima sprint,': 'Recommend: (1) activate search in production next sprint,',
    '(2) integrar SharePoint en Q3 para documentos corporativos, (3) expandir a': '(2) integrate SharePoint in Q3 for corporate documents, (3) expand to',
    'análisis de tendencias en Q4. La inversión inicial de $15K generará $120K en': 'trend analysis in Q4. Initial $15K investment generates $120K in',
    'ahorros anuales por reducción de tiempo de búsqueda.': 'annual savings from search time reduction.',
    'Hemos implementado un sistema de IA usando ML y NLP. Se indexaron documentos': 'Implemented an AI system using ML and NLP. Indexed documents',
    'en la nube. El sistema funciona bien y es escalable. Se pueden hacer muchas': 'in the cloud. System works well and is scalable. Can do many',
    'cosas con esto. Recomendamos implementarlo pronto. Será útil para los usuarios.': 'things with this. Recommend implementing soon. Will be useful to users.',
    '✅ Números concretos (2,345, 15min→30s, 200 users, 94%, 97%)': '✅ Concrete numbers (2,345, 15min→30s, 200 users, 94%, 97%)',
    '✅ Beneficio específico (reducción de tiempo de búsqueda)': '✅ Specific benefit (search time reduction)',
    '✅ Métrica de éxito (94% en primer resultado)': '✅ Success metric (94% on first result)',
    '✅ Escalabilidad demostrada (5,000 docs)': '✅ Demonstrated scalability (5,000 docs)',
    '✅ ROI cuantificado ($120K savings)': '✅ Quantified ROI ($120K savings)',
    '✅ Next steps concretos (sprint, Q3, Q4)': '✅ Concrete next steps (sprint, Q3, Q4)',
    '✅ Tono: Confianza sin arrogancia': '✅ Tone: Confidence without arrogance',
    '❌ Jerga sin contexto (ML, NLP, ML)': '❌ Jargon without context (ML, NLP, ML)',
    '❌ Adjetivos sin datos (bien, escalable, útil)': '❌ Adjectives without data (good, scalable, useful)',
    '❌ Vaguedad total (muchas cosas, pronto)': '❌ Total vagueness (many things, soon)',
    '❌ Sin métricas de éxito': '❌ No success metrics',
    '❌ Sin números concretos': '❌ No concrete numbers',
    '❌ Sin ROI o valor': '❌ No ROI or value',
    '❌ Tono: Poco profesional, poco convincente': '❌ Tone: Unprofessional, unconvincing',
    # Handle single words
    'profesional': 'professional',
    'accesible': 'accessible',
}

def translate_file(filepath: Path) -> int:
    """Translate Spanish content in a file. Returns number of replacements."""
    content = filepath.read_text(encoding='utf-8')
    original = content

    for spanish, english in TRANSLATION_MAP.items():
        content = content.replace(spanish, english)

    if content != original:
        filepath.write_text(content, encoding='utf-8')
        return 1
    return 0

# Files to process
files_to_translate = [
    (r'c:\repo\awesome-copilot\skills\rag-report-generator\report-generator.py', 'main'),
    (r'c:\repo\awesome-copilot\skills\rag-report-generator\report-templates.py', 'main'),
    (r'c:\repo\awesome-copilot\RAG-Azure-Builder-src\.github\skills\rag-report-generator\report-generator.py', 'submodule1'),
    (r'c:\repo\awesome-copilot\RAG-Azure-Builder-src\.github\skills\rag-report-generator\report-templates.py', 'submodule1'),
    (r'c:\repo\awesome-copilot\spec-kit-extension-rag-azure-builder\assets\rag-azure-builder\skills\rag-report-generator\report-generator.py', 'submodule2'),
    (r'c:\repo\awesome-copilot\spec-kit-extension-rag-azure-builder\assets\rag-azure-builder\skills\rag-report-generator\report-templates.py', 'submodule2'),
]

for filepath_str, repo_type in files_to_translate:
    filepath = Path(filepath_str)
    if filepath.exists():
        translate_file(filepath)
        print(f"✓ Translated: {filepath_str}")
    else:
        print(f"✗ Not found: {filepath_str}")

print("Done!")

