apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: awesome-copilot-location
  description: Links to additional entities in the awesome-copilot repository.
  annotations:
    github.com/project-slug: Bandwidth/awesome-copilot
spec:
  targets:
    - ./component.yaml
