/**
 * Client-side Pagefind adapter.
 *
 * Pagefind is generated by a post-build step (see
 * `src/integrations/pagefind-resources.ts`), so `/pagefind/pagefind.js` only
 * exists in a real build. The import is therefore lazy and guarded: in `astro
 * dev` it simply fails and search degrades to the static in-memory index.
 */
import { pageHref } from "./pageHref";
import { categoryOf, filterSearchItemsByLocale, mergeSearchItems, type SearchItem } from "./searchIndex";

type PagefindResultData = {
  url: string;
  excerpt?: string;
  meta?: Record<string, string | undefined>;
};

/** Strip HTML tags, repeating until no more tags remain so a malformed or
 * nested markup fragment (e.g. `<<script>script>`) can't survive a single pass. */
function stripTags(html: string): string {
  let text = html;
  let previous: string;
  do {
    previous = text;
    text = text.replace(/<[^>]*>/g, " ");
  } while (text !== previous);
  return text;
}
type PagefindModule = {
  options?: (opts: Record<string, unknown>) => Promise<void>;
  init?: () => Promise<void>;
  debouncedSearch?: (
    term: string,
    options?: unknown,
    debounceMs?: number,
  ) => Promise<{ results: { data: () => Promise<PagefindResultData> }[] } | null>;
  search: (
    term: string,
    options?: unknown,
  ) => Promise<{ results: { data: () => Promise<PagefindResultData> }[] }>;
};

/** Site base path, matching the value bootstrapped by `BaseLayout.astro`. */
function basePath(): string {
  const fromDocument =
    typeof document !== "undefined"
      ? document.documentElement.dataset.basePath
      : undefined;
  const base = fromDocument || pageHref();
  return base.endsWith("/") ? base : `${base}/`;
}

let modulePromise: Promise<PagefindModule | null> | null = null;

/** Match Pagefind's language selection, not an untranslated URL prefix. */
export function currentSearchLocale(): string {
  return typeof document !== "undefined"
    ? document.documentElement.lang?.toLowerCase() || "en"
    : "en";
}

/** Load (once) the Pagefind bundle, or resolve to `null` when unavailable. */
export function loadPagefind(): Promise<PagefindModule | null> {
  if (modulePromise) return modulePromise;
  modulePromise = (async () => {
    if (typeof window === "undefined") return null;
    try {
      const url = `${basePath()}pagefind/pagefind.js`;
      const mod: PagefindModule = await import(/* @vite-ignore */ url);
      await mod.options?.({ baseUrl: basePath() });
      await mod.init?.();
      return mod;
    } catch {
      // No index (dev server, or a build that skipped Pagefind) — the caller
      // falls back to the static index.
      return null;
    }
  })();
  return modulePromise;
}

/** Pagefind custom records carry a `Title — Agent` style suffix; strip it. */
function cleanTitle(title: string): string {
  return title.replace(/\s+—\s+(Agent|Instruction|Skill|Hook|Workflow|Plugin|Tool|Extension|Canvas)$/u, "");
}

export function pagefindItem(entry: PagefindResultData, base = "/"): SearchItem {
  const href = entry.meta?.canonical || entry.url;
  return {
    title: entry.meta?.resourceTitle ||
      cleanTitle(entry.meta?.title?.trim() || entry.url),
    description: entry.meta?.description ||
      (entry.excerpt ? stripTags(entry.excerpt) : ""),
    category: categoryOf(href, base),
    href,
    canonicalHref: entry.meta?.canonical,
    locale: entry.meta?.locale,
  };
}

/** Run a Pagefind query and adapt the hits to `SearchItem`s. */
export async function searchPagefind(
  term: string,
  limit: number,
  locale = currentSearchLocale(),
): Promise<SearchItem[]> {
  const pagefind = await loadPagefind();
  if (!pagefind) return [];
  try {
    const response = pagefind.debouncedSearch
      ? await pagefind.debouncedSearch(term, undefined, 180)
      : await pagefind.search(term);
    // `debouncedSearch` resolves to null when superseded by a newer query.
    if (!response) return [];
    let items: SearchItem[] = [];
    // Fetch bounded batches, but apply the result limit after identity merging.
    for (let offset = 0; offset < response.results.length && items.length < limit; offset += limit) {
      const data = await Promise.all(
        response.results.slice(offset, offset + limit).map((result) => result.data()),
      );
      items = mergeSearchItems([
        ...items,
        ...filterSearchItemsByLocale(
          data.filter((entry) => entry?.url).map((entry) => pagefindItem(entry, basePath())),
          locale,
          basePath(),
        ),
      ]);
    }
    return items.slice(0, limit);
  } catch (error) {
    console.warn("[search] Pagefind query failed; using the static index.", error);
    return [];
  }
}
