name: Check Spelling

on:
  push:
    branches: [staged]
  pull_request:
    branches: [staged]

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print GITHUB_TOKEN
        run: echo "GITHUB_TOKEN=$GITHUB_TOKEN"
      
      - name: Check spelling with codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: false
