# .github/labeler.yml
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
